[display]
horizontal_padding = 3
vertical_padding = 2
width = 0
show_translation = "romaji"
translation_color = "#888888"
font_size = "medium"
bold = true
border = false
rounded_border = true
source = false
modes = ["proverb", "anime"]
seed = 0
centered = true
